"""Surveillance-data preprocessing comparison (Chapter 8).

Companion text: Avoiding Pitfalls in Epidemic Modeling, Chapter 8.
Builds a reproducible 60-day incidence series with a day-of-week reporting
pattern and fits R0 three ways (raw counts, 7-day moving average, day-of-week
deconvolution); recovered R0_hat values against the true baseline R0 are printed
at runtime.  Writes preprocessing_{timeseries,fits,periodograms}.pdf.
Seeded (rng = default_rng(7)) for reproducibility.

Author:  James M. Hyman, mhyman@tulane.edu, Tulane University
Date:    2026-06-22   Version 1.1
"""
import numpy as np, matplotlib.pyplot as plt
from scipy.integrate import solve_ivp
from numpy.fft import rfft, rfftfreq
plt.rcParams.update({'font.family':'serif','font.size':10,'mathtext.fontset':'cm','axes.linewidth':0.8})
rng=np.random.default_rng(7)
from sir_i_model import BASE  # Phase 2 (S17): baseline centralized
cS,cIc,cR=BASE['c_S'],BASE['c_I'],BASE['c_R']; TAUM=BASE['tau_m']; nu=1/TAUM; Npop=1_000_000
def rhs(t,y,beta,gR):
    S,I,R=y; C=cS*S+cIc*I+cR*R; inf=cS*cIc*beta*S*I/C
    return [nu-inf-nu*S, inf-(gR+nu)*I, gR*I-nu*R]
def model_counts(beta,tauR,days):
    s=solve_ivp(rhs,[0,days.max()+1],[0.999,0.001,0.0],args=(beta,1/tauR),dense_output=True,rtol=1e-9,atol=1e-12,max_step=0.5)
    S,I,R=s.sol(days); C=cS*S+cIc*I+cR*R
    return cS*cIc*beta*S*I/C*Npop
beta0,tauR0=BASE['beta'],BASE['tau_R']; R0_true=cIc*beta0/(1/tauR0+nu)
NDAYS=60; days=np.arange(NDAYS)
counts_true=model_counts(beta0,tauR0,days)
w=np.array([1.10,1.10,1.10,1.15,1.20,0.65,0.70])  # Mon..Sun
obs=rng.poisson(np.clip(counts_true*w[days%7],0,None)).astype(float)

def ma7(x):
    o=np.full_like(x,np.nan)
    for i in range(len(x)):
        a,b=max(0,i-3),min(len(x),i+4); o[i]=x[a:b].mean()
    return o
# regression-based day-of-week deconvolution: log(obs)=a+b t+c t^2 + sum d_k 1[dow=k]
t=days.astype(float); D=np.column_stack([np.ones_like(t),t,t*t]+[ (days%7==k).astype(float) for k in range(7)])
y=np.log(np.clip(obs,1,None)); coef,*_=np.linalg.lstsq(D,y,rcond=None)
dk=coef[3:]; dk=dk-dk.mean(); fac=np.exp(dk)
raw=obs.copy(); mav=ma7(obs); dow=obs/fac[days%7]

# documented recovered (beta_hat, tauR_hat); R0_hat recomputed with new nu
# regenerated by tools/ch8_refit_preprocessing.py (documented protocol: 60-day window,
# Poisson-weighted residuals, seed 7) at the approved baseline.  Pending Zhuolin sign-off.
fits=[("Raw",0.0393,12.61),("7-day moving average",0.0407,11.59),("DoW deconvolution",0.0393,12.37)]
B='#1f5fa8'; Rd='#c0392b'; G='#2e7d32'

# Fig 1: timeseries
fig,ax=plt.subplots(3,1,figsize=(7.0,6.2),sharex=True)
for a,(lab,ser) in zip(ax,[('Raw (injected day-of-week effect)',raw),('7-day moving average',mav),('Day-of-week deconvolution',dow)]):
    a.plot(days,counts_true,'k-',lw=1.4,label='ground truth $\\mathsf{J}_{\\mathrm{true}}$',zorder=3)
    a.plot(days,ser,'o-',ms=3,lw=0.8,color=B,alpha=0.85,label=lab)
    a.legend(frameon=False,fontsize=8,loc='upper left'); a.set_ylabel('daily cases')
    for s in('top','right'):a.spines[s].set_visible(False)
ax[-1].set_xlabel('Day'); fig.tight_layout(); fig.savefig('figs/preprocessing_timeseries.pdf'); plt.close(fig); print('ts ok')

# Fig 2: periodograms
fig,ax=plt.subplots(figsize=(7.0,3.6))
for ser,lab,c,st in [(raw,'Raw',Rd,'-'),(mav,'7-day moving average',G,'--'),(dow,'day-of-week deconvolution',B,':')]:
    x=np.nan_to_num(ser-np.nanmean(ser)); P=np.abs(rfft(x))**2; f=rfftfreq(len(x),1)
    ax.semilogy(f[1:],P[1:]+1e-2,lw=1.3,label=lab,color=c,ls=st)
ax.axvline(1/7,color='0.5',ls='--',lw=1); ax.text(1/7+0.008,ax.get_ylim()[1]*0.25,'$1/7$ day$^{-1}$',fontsize=8)
ax.set_xlabel('frequency (day$^{-1}$)'); ax.set_ylabel('power'); ax.legend(frameon=False,fontsize=8)
for s in('top','right'):ax.spines[s].set_visible(False)
fig.tight_layout(); fig.savefig('figs/preprocessing_periodograms.pdf'); plt.close(fig); print('pg ok')

# Fig 3: fits (data + truth curve + fit curve from documented params)
sers={'Raw':raw,'7-day moving average':mav,'DoW deconvolution':dow}
fig,ax=plt.subplots(1,3,figsize=(9.6,3.2),sharey=True)
for a,(lab,b,tt) in zip(ax,fits):
    R0h=cIc*b/(1/tt+nu)
    a.plot(days,counts_true,'k-',lw=1.0,alpha=0.6,label=f'Truth ($\\mathcal{{R}}_0$={R0_true:.3f})')
    a.plot(days,sers[lab],'o',ms=2.5,color='0.45',alpha=0.7,label='Data')
    a.plot(days,model_counts(b,tt,days),'--',lw=1.6,color=Rd,label=f'Fit ($\\mathcal{{R}}_0$={R0h:.3f})')
    a.axvline(30,color='0.6',ls=':',lw=1); a.set_title(lab,fontsize=10); a.set_xlabel('Day')
    a.legend(frameon=False,fontsize=7.5,loc='upper left')
    for s in('top','right'):a.spines[s].set_visible(False)
ax[0].set_ylabel('daily cases'); fig.tight_layout(); fig.savefig('figs/preprocessing_fits.pdf'); plt.close(fig); print('fits ok')
print(f'truth R0={R0_true:.4f}; labels: '+', '.join(f"{l}={cIc*b/(1/t+nu):.3f}" for l,b,t in fits))
